# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Microsoft Azure Sponsorship(8cc247e6-5a1d-40b7-be6c-7d0a8c5ffa87)'
    subscriptionId: '8cc247e6-5a1d-40b7-be6c-7d0a8c5ffa87'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'niteco-hei-dev'
    location: 'Southeast Asia'
    templateLocation: 'Linked artifact'
    csmFile: 'azuredeploy.json'
    deploymentMode: 'Incremental'
